apiVersion: v1
kind: Service
metadata:
  name: pyapp-service
  labels:
    app: pyapp
spec:
  selector:
    app: pyapp
  ports:  
  - port: 80
    protocol: "TCP"
    targetPort: 8000
  type: LoadBalancer

