apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyapp
  labels:
    app: pyapp
spec:
  replicas: 3
  selector:
     matchLabels: 
       app: pyapp
  template:
    metadata:
      labels:
         app: pyapp
    spec:
      containers:
        - name: pyapp-c1
          image: lehardocker/pyapp:v1
          ports:
          - containerPort: 8000


    