name: Kubernetes CI
on: 
  push:
    branches:
    - master
jobs:
  pyapp-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4
      - name: Build Docker Image
        run: "docker build -t lehardocker/pyapp:${GITHUB_SHA::7} ."
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
      - name: Push Docker Image to Docker Hub
        run: "docker push lehardocker/pyapp:${GITHUB_SHA::7}"    
      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod a+x /usr/local/bin/yq
      - name: Update deployment.yml file with latest docker tag
        run: |
          # Short commit hash
          SHORT_SHA =${GITHUB_SHA::7}
          # Update image tag in deployment.yml file
          yq -i '.spec.template.spec.containers[0].image = "lehardocker/pyapp:'"$SHORT_SHA"'' ./k8s/pyappdeployment.yml
      

  
        




      
